### PR TITLE
Use pnpm instead of npm in build instructions

### PR DESCRIPTION
**Pull request by Mixaz017**
- [x] Remove mentions of npm in readme
- [x] Create a GH action job to automatically release nightly

### CODE REVIEW

**Comment by Mixaz017** [comment]
(except ubuntu users)

**Comment by Mixaz017** [comment]
Actually though, now that we require Node 16+ (because of pnpm), Ubuntu users are in shambles since Ubuntu LTS still ships Node 12. And average Ubuntu users have no idea what they're doing.
However, I don't think this is a big issue, since the main point of providing pre-built artifacts via GH action is so that users don't have to build the client from source if they just want to follow HEAD (as we discussed before). Users trying to modify crankshaft actually know what they're doing, so it won't be a problem if we just link to the official installation guide.

**Comment by KraXen72** [comment]
wait so pre-built artifacts are already set up?? or? that would be okay then.

**Comment by Mixaz017** [comment]
No. This is a draft PR, it's not done. See the task list.

**Comment by KraXen72** [comment]
i accidentally marked it as ready lol is it possible to change back

**Comment by Mixaz017** [comment]
Let's just pretend like it didn't happen XD

**Comment by Mixaz017** [comment]
The upload thing seems to be working, although currently all artifacts are put into a single zip file. We can split them by giving them a different `name` attribute in the workflow file, but how specific should it be? I'm thinking of splitting them by OS. Splitting per file is possible, but it might make the workflow a bit dirty.
image

**Comment by KraXen72** [comment]
split them like this:
linux, mac, windows (has only setup-win-x64.exe), windows-other (has the other windows ones)

**Comment by Mixaz017** [comment]
Why not split Windows ones by setup / portable? I think its more intuitive for users.

**Comment by KraXen72** [comment]
most users on windows only need the x64 setup, so adding more options to the "default" windows zip could confuse them (many times someone asked which release version for windows).

**Comment by Mixaz017** [comment]
Since arch specific binaries are only useful if downloaded individually (to save network/disk space), so it's not very useful when zipped together. It might be better to ignore them and only upload the "universal" ones.

**Comment by KraXen72** [comment]
i can't really say anything about arch binaries. do as you wish

**Comment by Mixaz017** [comment]
To be honest, I'm starting to question if this is the right way to do it. It might be better to have automated nightly releases like [Neovim does](https://github.com/neovim/neovim/blob/master/.github/workflows/release.yml). This means we only provide binaries from the default branch (otherwise it's gonna be too messy), but that should be enough for most users.

**Comment by KraXen72** [comment]
i don't like that because it will clutter the releases tab. build artificacts are fine imo and sure it can be only from master, feature specific branches don't need to have artifacts as once a feature is ready for testing it would make sense for that branch to be merged into master

**Comment by Mixaz017** [comment]
I don't think it clutters the releases tab (take a look at [Neovim](https://github.com/neovim/neovim) releases). GitHub ignores prereleases and shows the latest regular release in the right sidebar of the repo, so the normal users are not affected.
Also, it's much easier to find compared to build artifacts (Actions tab → click latest run → download artifact → unzip).

**Comment by Mixaz017** [comment]
We can use a third party service to have a link that automatically redirects to the latest build artifact, but it's something I want to avoid if possible.
Another benefit of using releases is that it would be much nicer to work with if we want to implement auto updater in the future.

**Comment by KraXen72** [comment]
is it possible to show the latest release (stable) in the sidebar but if somebody clicks an releases then it shows all of them? i just don't want the first release people see in the sidebar a nightly, like the neovim repo has it.

**Comment by Mixaz017** [comment]
Uhh what do you mean? It's already like that. Except we don't have the "release build" thing like Neovim does. So the latest versioned release would appear in the sidebar (just like how it is currently), and if you go to releases page it'll show all of them including automated builds.

**Comment by KraXen72** [comment]
that's fine then

**Comment by KraXen72** [comment]
but also add a disclaimer somewhere that the nightly builds have no guarantee anything will work lol

**Comment by Mixaz017** [comment]
Yeah, we can have a template markdown file for release description so we can just say that in the template :)

**Comment by Mixaz017** [comment]
If changes are okay, I'll add a branch filter so it'll only trigger from the master branch, then we can merge.

**Comment by KraXen72** [comment]
thanks for all the work!

**Comment by KraXen72** [comment]
looks good, feel free to merg

**Pull request merged**
