### PR TITLE
Reimplement ad blocking to be compatible with resource swapper

### PR DESCRIPTION
**Pull request by thegu5**
Remaining tasks before merge:
- conditional import
- reevaluate constructor / the if block that initializes it (lots of repeated code... any way to avoid?)
- linked to above, simplifying variables in the requesthandler class
- figure out why electron can't find blockFilters.txt in the asar if it's not read in main.ts

### CODE REVIEW

**Comment by Mixaz017** [comment]
Can reproduce the build issue but I have no idea why

**Comment by paintingofblue** [comment]
is it not an issue with the cliqz adblocker package, since it **should** install `@remusao/smaz` but doesn't as you can see in the error

**Comment by KraXen72** [comment]
maybe there's some misalignment between dev and build environments - is the esbuilder script with the same esbuild version used in the CI builds as well?n

**Comment by KraXen72** [comment]
i'll keep the todos in my project tracker note, but otherwise, good job! the code looks, fine. Thanks for your work!

**Pull request merged**
