### PR TITLE
Implement strict ESLint to ensure code quality and consistency.

### PR DESCRIPTION
**Pull request by asger-finding**
Consider using and familiarizing yourself with [ESLint](https://github.com/eslint/eslint) or [JavaScript Standard Style](https://github.com/standard/standard) to ensure code quality and consistency. Code linting should always be encouraged in a project.  

---

**Added dev dependencies**
 * eslint
 * eslint-config-airbnb-typescript
 * eslint-config-raven
 * eslint-plugin-import

### CODE REVIEW

**Comment by asger-finding** [comment]
Note that ESLint will throw a fit at the current code, as it doesn't meet the specific rules I've set for it. All errors should be fixable within a few hours.

**Comment by KraXen72** [comment]
i am already using [quick-lint-js](https://github.com/quick-lint/quick-lint-js) in my vs-code setup. are there any real benefits to using eslint to this?

**Comment by asger-finding** [comment]
You're already gitignoring any vscode folders. In addition, not everyone uses VSCode as their IDE, and ESLint even works in a CLI. ESLint is also far more popular, and it allows for extensive configuration, works for JS/TS, has plugin support and it's basically the gold standard. Look at literally any serious project, and you're probably gonna find ESLint. (vscode and electron even use it as a devDependency)

**Comment by KraXen72** [comment]
hmm, just checked and quick-lint-js says it doesen't support typescript *yet*, but 1) i had it before the typescript rewrite and the code is still like 60-70% the same, 2) the typescript server already tells you stuff like this.
 i don't really like eslint personally (really time-consuming to setup, strict and gives more headaches than actually help) but i might merge it if there is a big benefit.

**Comment by asger-finding** [comment]
oh, and it has 24 million weekly downloads as reported by npm.

**Comment by asger-finding** [comment]
I have already set up ESLint for you with plugins.

**Comment by KraXen72** [comment]
i am considering it. from what i can see off the bat:
- indent should be indent with tabs, size: 4
- it should not care about "" vs '' 
- i know interfaces shouldnt be camelcase but i can't get used to them being pascalcase
- it should not require me to add semicolons in ts as the compiled js already adds them for me (because of "use strict")
and probably a few other things. for now it just seems like too much effort for me to get used to this strict, alien formatting/style of code for me, with little to no benefit 

like i should change all my == to === but p sure i can set that up in tsconfig and don't need 4 more devdependencies...
if you feel like modifying the config so it has the stuff i mentioned above, i *might* merge it, but dont' wanna promise anything. as i said, there is little to no benefit for me currently...

**Comment by asger-finding** [comment]
I'm not going to work with blatant negligence and terrible code practice.

**Comment by KraXen72** [comment]
lmfao, okay. i appreciate people contributing, but i think i gave pretty good reasonings why it is not worth for me to use this.

**Comment by asger-finding** [comment]
Yes, you gave a fantastic reason why I shouldn't have bothered with this client in the first place.

**Comment by KraXen72** [comment]
After a chat with mixaz, there were some good points why this would be useful:
- this is an open source app, anyone can contribute and if many people contribute their code styles would mix => inconsistencies
- a lot better scalable
  i would customize some of the rules later on, but this would be useful. i have to leave really soon but i can merge when i'm back.

**Comment by asger-finding** [comment]
I appreciate you reconsidering the pull request. Code consistency was indeed the biggest deciding factor in implementing ESLint. Sorry for the unprofessional comments, I was just caught up in the heat of the moment 😅

Consider keeping most rules strict. If it's absolutely necessary to ignore a rule, that can be done case-by-case.  

I've already had a go at using an even stricter version of what I've commited here, and I've written 1958 lines of TypeScript with no errors, no mentions of the `any` type, et cetera. The current configuration is definitely viable.

PS: The configuration is already set to use tabs. There's no such thing as "size 4" tabs, that's configured directly in the IDE, which is also the appeal of tabs in the first place. See image below.

image

**Comment by KraXen72** [comment]
okay, will do so a bit later

**Comment by KraXen72** [comment]
ok so i merged it and it seems eslint is not complaining at all? i assume that' because you ran it with the fix flag and then manually fixed the rest? maybe i'm just not initializing eslint somehow, idk

**Comment by KraXen72** [comment]
forgot to npm i lol

**Comment by KraXen72** [comment]
@asger-finding merged, and configured eslint, edited my code so it works w it, but also disabled some rules. you might wanna check if i disabled too many 😅

**Comment by asger-finding** [comment]
With all due respect, you don't really get it, do you? By disabling 3/4ths of the rules for the project, you're just jumping through hoops rather than addressing the issues. Disable no inline comments? Now contributors have both the option to add the before **and** on the line.

It all comes down to code consistency, which you **will not** get with a loose linter. As I said previously, I've been able to write 2k lines of code with my strict configuration. You should be able to, too.

**Comment by KraXen72** [comment]
okay. i might reenable rules. but some were just a hassle, really. (sorry for wall of text)
here are reasonings why i tured off rules:
- no use before define: eslint doesen't quite understand (or something idk) that i can set up an eventlistener on domcontentloaded to an function that will be defined later, since the event will not fire before the function gets defined...
- no throw literal: most literal errors are just sanity checks anyway and don't need to be an object, a string is fine
- semi: i mentioned this before, but i do not want to  have semicolons at the end of each line, because typescript will automatically add them anyway.
- no-alert: i could just ignore the 1 alert i have, but this is a webapp that does utilize alerts as a way to communicate something to the user. i am not importing the electron remote module and using dialog just to display a message
- complexity: didn't understand the rule fully, but i got that i should extract stuff out of the 1 arrow function, but it already is pretty simple to follow..
- i'm currently kinda split about max len, because i use it to inject some svgs as raw text. i could have the m in separate files but it's more performance intensive to read a file and pass it to js that just having the string in there. again, could just ignore the specific occasions probably..
- id-len: i almost kept this enabled, but i use one character ids in mehod arrow functions where it is already really obvious what they stand for. like if the whole block is about userscript having a forEach(u => whatever) is pretty understandable.
- prefer-destructuring: didnt' understand the rule,  i didn't even know array destructuring is a thing... tried googling it but didn't understand either.
-  sort-imports, i tried to keep it enabled and have eslint automatically fix that, even imported a plugin to do that, but i couldn't get it to work after 20 minutes i gave up and disabled the rule.
- ts/ban-types: really tried to keep this enabled, but i didn't really know for what else to change the generic types like Object and Function
- some stuff i only set as warnings if not curcial, and eslint should fix it with --fix anyway, for example the single vs double quotes.

i can reenable the no-inline-comments and line-comment-position so they are consistent, as you said
i should probably reenable no-empty, empty catch statements are just a pain waiting to happen.
  
and then my code uses some edge-case things that electron specifically has, for example every electron function that returns something almost always returns the event as first parameter, so if i want to access other params, i have to first acknowledge that the first one is the event and then work with the rest. but eslint is complaining about unused paramteters. since i use a lot of electron functions, it is just easier to disable the rule rather than to ignore every time i use it.

COMMENTS:
 i want comments to be whereever/however just for me and if someone is contributing stuff that is too overly commented or inconsistent, i'd request changes to either remove the comments or modify them.
- ts comments. i use them really sparingly when it makes sense and it's just more effort to add both an eslint ignore comment and ts-ignore if i want to ts-ignore
- todo comments. why does eslint care about those? they're for me to know what to rewrite/implement next...

eslint by itself has many many default rules enabled, so by disabling 10 or so how i did should still keep the code pretty strict/consistent.  
i haven't used eslint too much so probably there are better ways to modify the rule than just disable it completely, but i really did try to first rather fix my code than to disable a rule.

i know this might be annoying but please do tell me what rules i should reenable and why, + how to fix my code (how you mentioned the comments) if you still have hope with me 😅

**Comment by Mixaz017** [comment]
You definitely should re-enable semi - JS/TS ASI can be very frustrating to deal with and can lead to unintended behaviors that are hard to track down.

For example: tsc will refuse to compile the code below because it has a syntax error. This code could be a proper code if I wrote semicolons. Cases like this can be very hard to find in real environments and should be avoided by enabling the semi rule.
image

**Comment by KraXen72** [comment]
okay.

**Comment by KraXen72** [comment]
@asger-finding added back some rules and tightened others in [a0565f0](https://github.com/KraXen72/crankshaft/commit/a0565f0bcaa56a998a77d6bc8e4029e2b0baa3c9)

**Pull request merged**
